import type { Metadata } from 'next'
import './globals.css'
import { Karla } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const karla = Karla({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html className={karla.className} lang="en">
      <body className="flex bg-gray-100 font-family-karla">{children}</body>
    </html>
  )
}
